### ISSUE TITLE
Json mapper automatically converts integer lists into double lists.

### ISSUE THREAD

**Issue by sahandilshan** [wso2-extensions/siddhi-map-json#84]
**Description:**
When we send a list of integers in a JSON document, JSON mapper converts that integer list into a double list.

**Comment by BuddhiWathsala** [comment]
This issue occurs due to the reason that the Gson library has [this issue](https://github.com/google/gson/issues/1580). Since we are currently using Gson to convert JSON arrays to objects, this problem occurred.

As described in [this question](https://stackoverflow.com/questions/15507997/how-to-prevent-gson-from-expressing-integers-as-floats), we can use other libraries such as jackson to solve this issue.
